---
title: "Symbiont Ecology"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the data

```{r data_loading}
library(ggplot2)
library(RColorBrewer)
library(readr)
library(stringr)
library(forcats)
library(dplyr)

fullcubeHelix <- c("#673F03", "#7D3002", "#891901", "#A7000F", "#B50142", "#CD0778", "#D506AD", "#E401E7", "#AB08FF","#7B1DFF", "#5731FD","#5E8EFF", "#4755FF" ,"#6FC4FE", "#86E9FE", "#96FFF7", "#B2FCE3", "#BBFFDB", "#D4FFDD", "#EFFDF0")
shorthelix <- c("#A7000F", "#E401E7","#5E8EFF","#86E9FE","#B2FCE3")
elevenhelix <- c("#673F03", "#891901", "#B50142", "#D506AD", "#AB08FF", "#5731FD", "#4755FF", "#86E9FE", "#B2FCE3", "#D4FFDD", "#EFFDF0")
tenhelix <- c("#891901", "#B50142", "#D506AD", "#AB08FF","#000000","#4755FF" , "#86E9FE", "#B2FCE3", "#D4FFDD", "#EFFDF0")
#"#5731FD"
# setwd("C:/Users/shake/OneDrive/Documents/GitHub/SymbulationEmp/stats_scripts")

all_data <- read_table2("munged_area_mult-sym-10-s.dat") # Load data
all_data <- all_data %>% filter(update != "update") # remove extra header rows

all_data$update <- as.numeric(all_data$update) # Treat update as numeric
all_data$count <- as.numeric(all_data$count) # Treat count as numeric

all_data <- all_data %>% mutate(  # Create column for heat map label
                          Interaction_Rate = case_when(
                            interval == "-1_-.9" ~ "-1 to -0.8 (Parasitic)", 
                            interval == "-.9_-.8" ~ "-1 to -0.8 (Parasitic)",
                            interval == "-.8_-.7" ~ "-0.8 to -0.6 (Parasitic)", 
                            interval == "-.7_-.6" ~ "-0.8 to -0.6 (Parasitic)", 
                            interval == "-.6_-.5" ~ "-0.6 to -0.4 (Detrimental)", 
                            interval == "-.5_-.4" ~ "-0.6 to -0.4 (Detrimental)", 
                            interval == "-.4_-.3" ~ "-0.4 to -0.2 (Detrimental)",
                            interval == "-.3_-.2" ~ "-0.4 to -0.2 (Detrimental)", 
                            interval == "-.2_-.1" ~ "-0.2 to 0 (Nearly Neutral)",
                            interval == "-.1_0" ~ "-0.2 to 0 (Nearly Neutral)",
                            interval == "0_.1" ~ "0 to 0.2 (Nearly Neutral)",
                            interval == ".1_.2" ~ "0 to 0.2 (Nearly Neutral)",
                            interval == ".2_.3" ~ "0.2 to 0.4 (Positive)",
                            interval == ".3_.4" ~ "0.2 to 0.4 (Positive)",
                            interval == ".4_.5" ~ "0.4 to 0.6 (Positive)",
                            interval == ".5_.6" ~ "0.4 to 0.6 (Positive)",
                            interval == ".6_.7" ~ "0.6 to 0.8 (Mutualistic)",
                            interval == ".7_.8" ~ "0.6 to 0.8 (Mutualistic)",
                            interval == ".8_.9" ~ "0.8 to 1.0 (Mutualistic)",
                            interval == ".9_1" ~ "0.8 to 1.0 (Mutualistic)"
                          ),
                          
                          Rate = case_when( # Create column for vertical transmission rate label
                            treatment == 0.0 ~ "0%",
                            treatment == 0.05 ~ "5%",
                            treatment == 0.06 ~ "6%",
                            treatment == 0.07 ~ "7%",
                            treatment == 0.08 ~ "8%",
                            treatment == 0.09 ~ "9%",
                            treatment == 0.1 ~ "10%",
                            treatment == 0.2 ~ "20%",
                            treatment == 0.3 ~ "30%",
                            treatment == 0.4 ~ "40%",
                            treatment == 0.5 ~ "50%",
                            treatment == 0.6 ~ "60%",
                            treatment == 0.7 ~ "70%",
                            treatment == 0.8 ~ "80%",
                            treatment == 0.9 ~ "90%",
                            treatment == 1 ~ "100%",
                          )
)

# Reorder interaction rate factor to be in correct numeric order:
# - First, we turn interval into a numeric variable that just holds the first number of each bin
all_data$interval <- as.numeric(str_extract(all_data$interval, "^-*\\.*[:digit:]+"))
# - Next we convert Interaction_Rate to a factor
all_data$Interaction_Rate <- as.factor(all_data$Interaction_Rate)
# - Lastly, we reorder Interaction_Rate based on interval
all_data$Interaction_Rate <- fct_reorder(all_data$Interaction_Rate, all_data$interval)

# Sum numbers in each bin to get correct totals
all_data <- all_data %>% group_by(Interaction_Rate, seed, treatment, update) %>% summarise(count = sum(count)) %>% mutate(rep=seed)
```

## Histogram plots

Following are the histograms showing the interaction values for hosts and symbionts across conditions

#### 10 symbionts per host

```{r vt_10_symlimit_10_symbiont_phenotypes}
ggplot(all_data %>% filter(treatment==.1), aes(x=update,y=count, fill=Interaction_Rate), position='stack') + geom_area() +ylab("Count of Symbionts with Phenotype") + xlab("Evolutionary time (in updates)") +scale_fill_manual("Interaction Rate\n Phenotypes",values=tenhelix) + theme(panel.background = element_rect(fill='light grey', colour='black')) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + guides(fill = "none") + guides(fill = guide_legend())+ facet_wrap(~rep) + theme(axis.text.x = element_text(angle=90, hjust=1))
```


```{r vt_50_symlimit_10_symbiont_phenotypes}
ggplot(all_data %>% filter(treatment==.5), aes(x=update,y=count, fill=Interaction_Rate), position='stack') + geom_area() +ylab("Count of Symbionts with Phenotype") + xlab("Evolutionary time (in updates)") +scale_fill_manual("Interaction Rate\n Phenotypes",values=tenhelix) + theme(panel.background = element_rect(fill='light grey', colour='black')) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + guides(fill = "none") + guides(fill = guide_legend())+ facet_wrap(~rep) + theme(axis.text.x = element_text(angle=90, hjust=1))
```

